-- KG Operations Planner database schema
-- Run this once in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('admin', 'operation', 'basic');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.record_status as enum ('active', 'pause', 'closed');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role public.app_role not null default 'basic',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  address text not null,
  status public.record_status not null default 'active',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);

create table if not exists public.lorries (
  id bigint generated by default as identity primary key,
  registration_no text not null unique,
  driver_name text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);

create table if not exists public.foremen (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);

create table if not exists public.site_assignments (
  id uuid primary key default gen_random_uuid(),
  plan_date date not null,
  site_id bigint not null references public.sites(id) on delete restrict,
  lorry_id bigint references public.lorries(id) on delete set null,
  foreman_id bigint references public.foremen(id) on delete set null,
  shift text not null default 'day' check (shift in ('day','night','am','pm')),
  notes text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  unique(plan_date, site_id, shift)
);

create table if not exists public.assignment_workers (
  assignment_id uuid not null references public.site_assignments(id) on delete cascade,
  worker_id bigint not null references public.workers(id) on delete restrict,
  sort_order integer not null default 0,
  primary key (assignment_id, worker_id)
);

create table if not exists public.plan_sections (
  id uuid primary key default gen_random_uuid(),
  plan_date date not null,
  title text not null,
  body text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do update set email = excluded.email;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users
for each row execute procedure public.handle_new_user();

-- Backfill profiles if Auth users existed before this schema was installed.
insert into public.profiles (id, email, full_name)
select id, coalesce(email, ''), coalesce(raw_user_meta_data->>'full_name', '')
from auth.users
on conflict (id) do nothing;

create or replace function public.current_app_role()
returns public.app_role language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.can_edit_operations()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(public.current_app_role() in ('admin','operation'), false);
$$;

create or replace function public.touch_audit_columns()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  if tg_op = 'INSERT' then new.created_by = auth.uid(); end if;
  return new;
end; $$;

create or replace function public.touch_profile()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end; $$;

-- Recreate audit triggers safely.
do $$
declare t text;
begin
  foreach t in array array['sites','workers','lorries','foremen','site_assignments','plan_sections'] loop
    execute format('drop trigger if exists touch_%I on public.%I', t, t);
    execute format('create trigger touch_%I before insert or update on public.%I for each row execute procedure public.touch_audit_columns()', t, t);
  end loop;
end $$;

drop trigger if exists touch_profiles on public.profiles;
create trigger touch_profiles before update on public.profiles for each row execute procedure public.touch_profile();

-- Enable RLS.
alter table public.profiles enable row level security;
alter table public.sites enable row level security;
alter table public.workers enable row level security;
alter table public.lorries enable row level security;
alter table public.foremen enable row level security;
alter table public.site_assignments enable row level security;
alter table public.assignment_workers enable row level security;
alter table public.plan_sections enable row level security;

-- Profiles: each user sees their own profile; admins see all profiles.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (id = auth.uid() or public.current_app_role() = 'admin');

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated
using (public.current_app_role() = 'admin') with check (public.current_app_role() = 'admin');

-- Operational tables: all authenticated users may read; only Admin/Operation may write.
do $$
declare t text;
begin
  foreach t in array array['sites','workers','lorries','foremen','site_assignments','assignment_workers','plan_sections'] loop
    execute format('drop policy if exists %I_read on public.%I', t, t);
    execute format('create policy %I_read on public.%I for select to authenticated using (true)', t, t);
    execute format('drop policy if exists %I_insert on public.%I', t, t);
    execute format('create policy %I_insert on public.%I for insert to authenticated with check (public.can_edit_operations())', t, t);
    execute format('drop policy if exists %I_update on public.%I', t, t);
    execute format('create policy %I_update on public.%I for update to authenticated using (public.can_edit_operations()) with check (public.can_edit_operations())', t, t);
    execute format('drop policy if exists %I_delete on public.%I', t, t);
    execute format('create policy %I_delete on public.%I for delete to authenticated using (public.can_edit_operations())', t, t);
  end loop;
end $$;

-- Helpful indexes.
create index if not exists idx_assignments_date on public.site_assignments(plan_date);
create index if not exists idx_sections_date on public.plan_sections(plan_date);
create index if not exists idx_sites_status on public.sites(status);
create index if not exists idx_workers_status on public.workers(status);

-- API grants. RLS still controls each row/action.
grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.sites, public.workers, public.lorries, public.foremen, public.site_assignments, public.assignment_workers, public.plan_sections to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- The website automatically creates the temporary default Admin through the manage-users Edge Function.
